language: scala
scala:
- 2.11.8
script:
- sbt clean coverage test
after_success:
- sbt coverageReport coveralls
- .travis.d/scaladoc.sh
env:
  global:
  - secure: qQz/7+6ytFzJ8VlUeigvjnHpzmk6imP0mi4ouKtim4IChQSEQi/lgJHv8Cd45JSRW+/deh/gGAzS2HTpWIXpUZqLuuEwt07ungYInCRbVzTw7fb7LlLh5zePcOi5kvIsU8n3GzP7OB0lghhPgt3yqGj77YuAIzFfS79XLopLDzJD0r2MBbjoADvPM1k7nG2oWCbuPUyQXPGQJfYMQ5wysCdO+50zT2Hu83iGVjt5jFErUuMNDDeJiiQMpgVAQOoVTUcubT2VIMAmqjBAk9rQAJOcB/1TOvBfA0170vq9q6TUWFxF4Og0wW61NCMhztMijwOicUfOHPnCZgMkp/VodITZPbevfglOERsnAWg+1a/54qnYUaWM5rO3BIlZujqRSd3Ek4qc+giEk1ELnWlf+KCLJmViIK60/tGTW+xD8mwP+k3CoHHGd7W3cSgOZOEkkpIC/Ahv89wMvp+Fv1BOzQfI6slDXIrmwyMEnYw5Mw/eR2FtrftPo7itTtj+WQ5vepQbTvFxhrc2DIP4rnHpyXy7TYfWreJaXJIFd+nfckZb3vnt6mU9O8z4YNo4chMl3+C+kc0cNftbUDkDhH7gFFNnze8WZh6z2Wg+cmaFEm60UPuoYbehi/vWy1bCeheWpmeyBgHqULF2hSOk1ySCjM7Qm9scAAPltEV11ybNjQk=
  - secure: 0++UQ/FrW1j6gf6lfW0XeqtMwEsUY4WwRYctWMjczeyKMFZOWpkU1Arg9Tu0dZQCXXtEKS991BXIru+udDwcluqFB+Ny2Lf+E/D2WvapwAUAbbJWE8eNKuAMuR1HRG4h7xFdp89RYd8+jA3weUAm0SQLpr6RW4UawhpLkiiQ9djVoXqwHOxtFr9mJSqc03OHnsDUMrQ0cCZiANybdZnnsBnHCFQBfYR08KA9MBNzhVKKZvszrIexTI0g6qAeuFZ9TgNd+OA7hnuw/ZOBPZ5Oz0DlhGdS2gqQjrzn1raN/1Q63w7Ru8Pcsw4IUBQxt7BPdW/aAk6OEYsvjXNDHWN3pzjco9uLkSTPl2WzKascD0YiJy74SJqZyGIWfZOmbpwxF3jWy8xWeBHTKICBjkOzcJRJElGEKviJZ7IeEmOluy3DzThm/nL+b4+LjlfVK2SRSEqxK5mscIQ5EblzkYjAvqS3bTyMAPkvGUQHz4iMLtlB9m2Pqu+rpnNC82Yc4Xlb8dJ2bWhL2RqvELCq4uR8QoAIQtAIhbY/n77D7KCAHqWP+Z5DVqDGRywODVbL2oeFm8Ev4VhNhwKE8rNJfPaalv/txUyDb5SPXbPUzBhnC5mr1IJzs5723lpyfgbkeMcdC4dcBXlrSP+5ntU0DFVHwEgb23MfGfp9BgwIX0MomY0=
